version: "2"
run:
  modules-download-mode: readonly
  tests: false
output:
  formats:
    text:
      path: stdout
linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - nakedret
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dogsled:
      max-blank-identifiers: 2
    dupl:
      threshold: 150
    errcheck:
      check-type-assertions: false
      check-blank: false
    funlen:
      lines: 200
      statements: 50
    gocyclo:
      min-complexity: 20
    govet:
      enable:
        - atomicalign
      disable:
        - shadow
      enable-all: false
      disable-all: false
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 150
      tab-width: 1
    nakedret:
      max-func-lines: 30
    unparam:
      check-exported: false
    unused:
      exported-fields-are-used: false
    whitespace:
      multi-if: true
      multi-func: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - funlen
          - gosec
          - lll
          - mnd
          - scopelint
          - unused
        path: /mocks/
      - linters:
          - dupl
        path: exchange/
      - path: cmd/
        text: logging is allowed only by pkg/log
      - path: pkg/log/
        text: logging is allowed only by pkg/log
      - path: (.+)\.go$
        text: .*github.com/chronicleprotocol/suite/pkg/ethereum.*is deprecated.*
      - path: (.+)\.go$
        text: .*Use ethereumv2 package instead.*
    paths:
      - bin
      - testdata
      - testutil
      - e2e
      - third_party$
      - builtin$
      - examples$
issues:
  new: true
formatters:
  enable:
    - gofmt
  settings:
    goimports:
      local-prefixes:
        - github.com/chronicleprotocol/suite
  exclusions:
    generated: lax
    paths:
      - bin
      - testdata
      - testutil
      - e2e
      - third_party$
      - builtin$
      - examples$
