name: Publish Docker Image
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      version:
        description: 'New Version (no `v` prefix)'
        type: string
        required: false
        default: ''
jobs:
  build-and-push:
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: chronicleprotocol/actions-workflows/.github/workflows/docker-build-and-publish.yaml@main
    with:
      application: challenger-go
      version: ${{ inputs.version }}
